name: Testing and Building my app
# on: ['push', 'workflow_dispatch']
# on: 
#   pull_request:
#     types: [opened, closed]
#   workflow_dispatch:  
# on: 
#   push:
#     branches: 
#       - main
#     paths:
#       - '**/*.js'
on: 
  push
jobs:
    test:
        runs-on: ubuntu-slim
        steps:
            - name: getting my code first
              # pulls your repo into the runner so the workflow can access it
              uses: actions/checkout@v6
            - name: installing node
              # installs Node.js version 24.14.0
              uses: actions/setup-node@v6
              with:
                node-version: '24.14.0'
            - name: installing dependencies
              run: npm install
            - name: testing app
              run: npm test
    build:
        needs: test
        runs-on: ubuntu-slim
        steps:
            - name: getting my code first
              # pulls your repo into the runner so the workflow can access it
              uses: actions/checkout@v6
            - name: installing node
              # installs Node.js version 24.14.0
              uses: actions/setup-node@v6
              with:
                node-version: '24.14.0'
            - name: installing dependencies
              run: npm install
            - name: start my app
              run: npm run build              